// Habilidades da BNCC — Matemática, Ensino Fundamental (1º ao 9º ano)
// Fonte: Base Nacional Comum Curricular (Matemática, EF), reorganizada por ano/unidade temática.
// O bimestre é uma distribuição pedagógica sugerida (a BNCC não define bimestres),
// calculada automaticamente dividindo a sequência oficial de cada ano em 4 blocos.

export type UnidadeTematica =
  | "NUMEROS"
  | "ALGEBRA"
  | "GEOMETRIA"
  | "GRANDEZAS_MEDIDAS"
  | "PROBABILIDADE_ESTATISTICA";

export interface HabilidadeSeed {
  codigo: string;
  anoEscolar: number;
  unidadeTematica: UnidadeTematica;
  descricao: string;
  bimestre: number; // preenchido automaticamente abaixo
}

type RawHabilidade = [codigo: string, unidade: UnidadeTematica, descricao: string];

const ANO_1: RawHabilidade[] = [
  ["EF01MA01", "NUMEROS", "Utilizar números naturais como indicador de quantidade ou de ordem."],
  ["EF01MA02", "NUMEROS", "Contar de maneira exata ou aproximada, utilizando diferentes estratégias como pareamento e agrupamento."],
  ["EF01MA03", "NUMEROS", "Estimar e comparar quantidades de objetos de dois conjuntos (até 20 elementos)."],
  ["EF01MA04", "NUMEROS", "Contar a quantidade de objetos de coleções até 100 unidades e registrar o resultado."],
  ["EF01MA05", "NUMEROS", "Comparar números naturais de até duas ordens, indicando o maior ou o menor."],
  ["EF01MA06", "NUMEROS", "Construir fatos básicos da adição para uso em cálculos."],
  ["EF01MA07", "NUMEROS", "Compor e decompor número de até duas ordens por meio de diferentes adições."],
  ["EF01MA08", "NUMEROS", "Resolver e elaborar problemas de adição e de subtração, envolvendo números de até dois algarismos."],
  ["EF01MA09", "ALGEBRA", "Organizar e ordenar objetos por diferentes atributos (cor, forma, medida)."],
  ["EF01MA10", "ALGEBRA", "Descrever, após o reconhecimento de um padrão, os elementos ausentes em sequências recursivas."],
  ["EF01MA11", "GEOMETRIA", "Descrever a localização de pessoas e objetos no espaço, utilizando termos como direita, esquerda, em cima, embaixo."],
  ["EF01MA12", "GEOMETRIA", "Descrever a localização de pessoas e objetos utilizando pontos de referência."],
  ["EF01MA13", "GEOMETRIA", "Relacionar figuras geométricas espaciais a objetos familiares do mundo físico."],
  ["EF01MA14", "GEOMETRIA", "Identificar e nomear figuras planas em desenhos apresentados em diferentes disposições."],
  ["EF01MA15", "GRANDEZAS_MEDIDAS", "Comparar comprimentos, capacidades ou massas, utilizando termos como mais alto, mais baixo, mais pesado."],
  ["EF01MA16", "GRANDEZAS_MEDIDAS", "Ordenar eventos diários utilizando termos como antes, agora e depois."],
  ["EF01MA17", "GRANDEZAS_MEDIDAS", "Reconhecer e relacionar períodos do dia, dias da semana e meses do ano."],
  ["EF01MA18", "GRANDEZAS_MEDIDAS", "Registrar datas, com dia, mês e ano, utilizando calendário."],
  ["EF01MA19", "GRANDEZAS_MEDIDAS", "Reconhecer e relacionar valores de moedas e cédulas do sistema monetário brasileiro."],
  ["EF01MA20", "PROBABILIDADE_ESTATISTICA", "Classificar eventos envolvendo o acaso como certos, possíveis ou impossíveis."],
  ["EF01MA21", "PROBABILIDADE_ESTATISTICA", "Ler dados expressos em tabelas e em gráficos de colunas simples."],
  ["EF01MA22", "PROBABILIDADE_ESTATISTICA", "Realizar pesquisa envolvendo variáveis categóricas e organizar dados coletados por meio de representações."],
];

const ANO_2: RawHabilidade[] = [
  ["EF02MA01", "NUMEROS", "Comparar e ordenar números naturais até a ordem de centenas, com compreensão das principais características do sistema decimal."],
  ["EF02MA02", "NUMEROS", "Fazer estimativas por meio de estratégias diversas a respeito da quantidade de objetos de coleções e registrar o resultado."],
  ["EF02MA03", "NUMEROS", "Comparar quantidades de objetos por estimativa e/ou por correspondência, indicando 'tem mais', 'tem menos' ou 'tem a mesma quantidade'."],
  ["EF02MA04", "NUMEROS", "Compor e decompor números naturais de até três ordens, com suporte de material manipulável."],
  ["EF02MA05", "NUMEROS", "Construir fatos básicos da adição e subtração e utilizá-los no cálculo mental ou escrito."],
  ["EF02MA06", "NUMEROS", "Resolver e elaborar problemas de adição e subtração, com os significados de juntar, acrescentar, separar, retirar e comparar."],
  ["EF02MA07", "NUMEROS", "Resolver e elaborar problemas de multiplicação (por 2, 3, 4 e 5) com a ideia de adição de parcelas iguais."],
  ["EF02MA08", "NUMEROS", "Resolver e elaborar problemas envolvendo dobro, metade, triplo e terça parte."],
  ["EF02MA09", "ALGEBRA", "Construir sequências repetitivas e sequências recursivas por meio de números naturais."],
  ["EF02MA10", "ALGEBRA", "Descrever um padrão de sequências repetitivas e recursivas."],
  ["EF02MA11", "ALGEBRA", "Comparar igualdades, identificando a característica de equilíbrio, para justificar resultados."],
  ["EF02MA12", "GEOMETRIA", "Identificar e registrar, em linguagem verbal ou não verbal, a localização e os deslocamentos de pessoas e de objetos no espaço."],
  ["EF02MA13", "GEOMETRIA", "Esboçar roteiros a ser seguidos ou plantas de ambientes familiares, assinalando entradas, saídas e alguns pontos de referência."],
  ["EF02MA14", "GEOMETRIA", "Reconhecer, nomear e comparar figuras geométricas espaciais (cubo, bloco retangular, pirâmide, cone, cilindro e esfera)."],
  ["EF02MA15", "GEOMETRIA", "Reconhecer, comparar e nomear figuras planas (círculo, quadrado, retângulo e triângulo)."],
  ["EF02MA16", "GRANDEZAS_MEDIDAS", "Estimar, medir e comparar comprimentos de lados de salas usando unidades de medida não padronizadas e padronizadas."],
  ["EF02MA17", "GRANDEZAS_MEDIDAS", "Estimar, medir e comparar capacidade e massa, utilizando estratégias pessoais e unidades de medida não padronizadas ou padronizadas."],
  ["EF02MA18", "GRANDEZAS_MEDIDAS", "Indicar a duração de um intervalo de tempo entre duas datas, com o apoio de calendário."],
  ["EF02MA19", "GRANDEZAS_MEDIDAS", "Medir a duração de um intervalo de tempo por meio de relógio digital e associar o horário ao período do dia."],
  ["EF02MA20", "GRANDEZAS_MEDIDAS", "Estabelecer a equivalência de valores entre moedas e cédulas do sistema monetário brasileiro."],
  ["EF02MA21", "PROBABILIDADE_ESTATISTICA", "Classificar eventos, em situações do cotidiano, como 'ocorrerá com certeza', 'talvez ocorra' ou 'é impossível ocorrer'."],
  ["EF02MA22", "PROBABILIDADE_ESTATISTICA", "Comparar informações de pesquisas apresentadas por meio de tabelas de dupla entrada e em gráficos de colunas."],
  ["EF02MA23", "PROBABILIDADE_ESTATISTICA", "Realizar pesquisa em universo de até 30 elementos, organizando os dados coletados em listas, tabelas e gráficos de colunas."],
];

const ANO_3: RawHabilidade[] = [
  ["EF03MA01", "NUMEROS", "Ler, escrever e comparar números naturais até a ordem de unidade de milhar."],
  ["EF03MA02", "NUMEROS", "Identificar características do sistema de numeração decimal por meio da composição e decomposição de número de até quatro ordens."],
  ["EF03MA03", "ALGEBRA", "Construir e utilizar fatos básicos da adição e da multiplicação para o cálculo mental ou escrito."],
  ["EF03MA04", "NUMEROS", "Estabelecer a relação entre números naturais e pontos da reta numérica para utilizá-la na ordenação dos números naturais."],
  ["EF03MA05", "NUMEROS", "Utilizar diferentes procedimentos de cálculo mental e escrito para resolver problemas de adição e subtração."],
  ["EF03MA06", "NUMEROS", "Resolver e elaborar problemas de adição e subtração com os significados de juntar, acrescentar, separar, retirar e comparar."],
  ["EF03MA07", "NUMEROS", "Resolver e elaborar problemas de multiplicação (por 2, 3, 4, 5 e 10) com os significados de adição de parcelas iguais e elemento faltante."],
  ["EF03MA08", "NUMEROS", "Resolver e elaborar problemas de divisão de um número natural por outro (até 10), com resto zero e diferente de zero."],
  ["EF03MA09", "NUMEROS", "Associar o quociente de uma divisão com resto zero de um número natural por 2, 3, 4, 5 e 10 às ideias de metade, terça, quarta e quinta partes."],
  ["EF03MA10", "ALGEBRA", "Identificar regularidades em sequências numéricas compostas por múltiplos de um número natural."],
  ["EF03MA11", "ALGEBRA", "Compreender a ideia de igualdade para escrever diferentes sentenças de adições ou de subtrações de dois números naturais que resultem na mesma soma ou diferença."],
  ["EF03MA12", "GEOMETRIA", "Descrever a localização de pessoas e objetos no espaço, segundo um dado ponto de referência, e a movimentação por meio de esquemas, croquis e outras representações."],
  ["EF03MA13", "GEOMETRIA", "Associar figuras geométricas espaciais a objetos do mundo físico e nomear essas figuras (cubo, bloco retangular, pirâmide, cone, cilindro e esfera)."],
  ["EF03MA14", "GEOMETRIA", "Descrever características de algumas figuras geométricas espaciais, relacionando-as com suas planificações."],
  ["EF03MA15", "GEOMETRIA", "Classificar e comparar figuras planas em relação aos lados e vértices, e nomeá-las."],
  ["EF03MA16", "GEOMETRIA", "Reconhecer figuras congruentes, usando sobreposição e desenhos em malhas quadriculadas ou triangulares."],
  ["EF03MA17", "GRANDEZAS_MEDIDAS", "Reconhecer que o resultado de uma medida depende da unidade de medida utilizada."],
  ["EF03MA18", "GRANDEZAS_MEDIDAS", "Escolher a unidade de medida e o instrumento mais apropriado para medições de comprimento, tempo e capacidade."],
  ["EF03MA19", "GRANDEZAS_MEDIDAS", "Estimar, medir e comparar comprimentos, utilizando unidades de medida não padronizadas e padronizadas mais usuais (metro, centímetro e milímetro)."],
  ["EF03MA20", "GRANDEZAS_MEDIDAS", "Estimar, medir e comparar capacidade e massa, utilizando unidades de medida não padronizadas e padronizadas mais usuais (litro, mililitro, quilograma, grama e miligrama)."],
  ["EF03MA21", "GRANDEZAS_MEDIDAS", "Comparar, visualmente ou por superposição, áreas de faces de objetos, de figuras planas ou de desenhos."],
  ["EF03MA22", "GRANDEZAS_MEDIDAS", "Ler horas em relógios digitais e em relógios analógicos e reconhecer a relação entre hora e minuto e entre minuto e segundo."],
  ["EF03MA23", "GRANDEZAS_MEDIDAS", "Ler e registrar medidas e intervalos de tempo, utilizando relógios (analógico e digital) para informar o início, o fim e a duração de um evento."],
  ["EF03MA24", "GRANDEZAS_MEDIDAS", "Resolver e elaborar problemas que envolvam a comparação e a equivalência de valores monetários do sistema brasileiro."],
  ["EF03MA25", "PROBABILIDADE_ESTATISTICA", "Identificar, em eventos familiares aleatórios, todos os resultados possíveis, estimando os que têm maiores ou menores chances de ocorrência."],
  ["EF03MA26", "PROBABILIDADE_ESTATISTICA", "Resolver problemas cujos dados estão apresentados em tabelas de dupla entrada, gráficos de barras ou de colunas."],
  ["EF03MA27", "PROBABILIDADE_ESTATISTICA", "Ler, interpretar e comparar dados apresentados em tabelas de dupla entrada, gráficos de barras ou de colunas."],
  ["EF03MA28", "PROBABILIDADE_ESTATISTICA", "Realizar pesquisa envolvendo variáveis categóricas em um universo de até 30 elementos, organizar dados e construir gráfico de colunas."],
];

const ANO_4: RawHabilidade[] = [
  ["EF04MA01", "NUMEROS", "Ler, escrever e ordenar números naturais até a ordem de dezenas de milhar."],
  ["EF04MA02", "NUMEROS", "Mostrar, por decomposição e composição, que todo número natural pode ser escrito por meio de adições e multiplicações por potências de dez."],
  ["EF04MA03", "NUMEROS", "Resolver e elaborar problemas com números naturais envolvendo adição e subtração, utilizando estratégias diversas."],
  ["EF04MA04", "NUMEROS", "Utilizar as relações entre adição/subtração e multiplicação/divisão para ampliar as estratégias de cálculo."],
  ["EF04MA05", "NUMEROS", "Utilizar as propriedades das operações para desenvolver estratégias de cálculo."],
  ["EF04MA06", "NUMEROS", "Resolver e elaborar problemas envolvendo multiplicação de números naturais (adição de parcelas iguais, organização retangular e proporcionalidade)."],
  ["EF04MA07", "NUMEROS", "Resolver e elaborar problemas de divisão cujo divisor tenha até dois algarismos."],
  ["EF04MA08", "NUMEROS", "Resolver, com o suporte de imagem e/ou material manipulável, problemas simples de contagem envolvendo o princípio multiplicativo."],
  ["EF04MA09", "NUMEROS", "Reconhecer as frações unitárias mais usuais (1/2, 1/3, 1/4, 1/5, 1/10 e 1/100) como unidade de medida menor que uma unidade, utilizando a reta numérica."],
  ["EF04MA10", "NUMEROS", "Reconhecer que as regras do sistema de numeração decimal podem ser estendidas para a representação decimal de um número racional, associando décimos e centésimos a moedas e cédulas."],
  ["EF04MA11", "ALGEBRA", "Identificar regularidades em sequências numéricas compostas por múltiplos de um número natural."],
  ["EF04MA12", "ALGEBRA", "Reconhecer, por meio de investigações, que há grupos de números naturais para os quais as divisões por um determinado número resultam em restos iguais."],
  ["EF04MA13", "ALGEBRA", "Reconhecer, por meio de investigações, utilizando a calculadora, as relações inversas entre as operações de adição e de subtração e de multiplicação e de divisão."],
  ["EF04MA14", "ALGEBRA", "Determinar o número desconhecido que torna verdadeira uma igualdade que envolve as operações fundamentais."],
  ["EF04MA15", "ALGEBRA", "Reconhecer, por meio de investigações, que a relação de igualdade entre dois termos permanece ao adicionar, subtrair, multiplicar ou dividir ambos os termos por um mesmo número."],
  ["EF04MA16", "GEOMETRIA", "Descrever deslocamentos e localização de pessoas e objetos no espaço, utilizando malhas quadriculadas e representações como plantas e mapas."],
  ["EF04MA17", "GEOMETRIA", "Associar figuras geométricas espaciais (prismas e pirâmides) a suas planificações."],
  ["EF04MA18", "GEOMETRIA", "Reconhecer ângulos retos e não retos em figuras poligonais com o uso de dobraduras, esquadros ou softwares."],
  ["EF04MA19", "GEOMETRIA", "Reconhecer simetria de reflexão em figuras e em pares de figuras geométricas planas."],
  ["EF04MA20", "GRANDEZAS_MEDIDAS", "Medir, estimar, comparar e ordenar comprimentos, massas e capacidades, utilizando unidades de medida padronizadas mais usuais."],
  ["EF04MA21", "GRANDEZAS_MEDIDAS", "Estimar e medir área de figuras planas por meio de malhas quadriculadas, considerando unidades de medida não padronizadas."],
  ["EF04MA22", "GRANDEZAS_MEDIDAS", "Estabelecer a relação entre o horário de início e término de um evento e sua duração, em horas, minutos e segundos."],
  ["EF04MA23", "GRANDEZAS_MEDIDAS", "Reconhecer temperatura como grandeza e o grau Celsius como unidade de medida a ela associada, e utilizá-lo em comparações."],
  ["EF04MA24", "GRANDEZAS_MEDIDAS", "Registrar as temperaturas máxima e mínima diárias, e elaborar gráficos representativos da variação da temperatura."],
  ["EF04MA25", "GRANDEZAS_MEDIDAS", "Resolver e elaborar problemas que envolvam situações de compra e venda e formas de pagamento, utilizando termos como troco e desconto."],
  ["EF04MA26", "PROBABILIDADE_ESTATISTICA", "Identificar, entre eventos aleatórios cotidianos, aquele que tem maior chance de ocorrência, reconhecendo características de resultados mais prováveis."],
  ["EF04MA27", "PROBABILIDADE_ESTATISTICA", "Analisar dados apresentados em tabelas simples ou de dupla entrada e em gráficos de colunas ou pictóricos, com base em informações das diferentes áreas do conhecimento."],
  ["EF04MA28", "PROBABILIDADE_ESTATISTICA", "Realizar pesquisa envolvendo variáveis categóricas e numéricas e organizar dados coletados por meio de tabelas e gráficos de colunas."],
];

const ANO_5: RawHabilidade[] = [
  ["EF05MA01", "NUMEROS", "Ler, escrever e ordenar números naturais até a ordem das centenas de milhar."],
  ["EF05MA02", "NUMEROS", "Ler, escrever e ordenar números racionais na forma decimal com compreensão das principais características do sistema de numeração decimal."],
  ["EF05MA03", "NUMEROS", "Identificar e representar frações (menores e maiores que a unidade), associando-as ao resultado de uma divisão ou à ideia de parte de um todo."],
  ["EF05MA04", "NUMEROS", "Identificar frações equivalentes."],
  ["EF05MA05", "NUMEROS", "Comparar e ordenar números racionais positivos (representações fracionária e decimal), relacionando-os a pontos na reta numérica."],
  ["EF05MA06", "NUMEROS", "Associar as representações 10%, 25%, 50%, 75% e 100% a frações e utilizá-las em situações que envolvem porcentagens."],
  ["EF05MA07", "NUMEROS", "Resolver e elaborar problemas de adição e subtração com números naturais e com números racionais, cuja representação decimal seja finita."],
  ["EF05MA08", "NUMEROS", "Resolver e elaborar problemas de multiplicação e divisão com números naturais e com números racionais cuja representação decimal seja finita."],
  ["EF05MA09", "NUMEROS", "Resolver e elaborar problemas de contagem envolvendo o princípio multiplicativo por meio de esquemas."],
  ["EF05MA10", "ALGEBRA", "Concluir, por meio de investigações, que a relação de igualdade entre dois membros permanece ao adicionar, subtrair, multiplicar ou dividir ambos os membros por um mesmo número."],
  ["EF05MA11", "ALGEBRA", "Resolver e elaborar problemas cuja conversão em sentença matemática seja uma igualdade com uma operação em que um dos termos é desconhecido."],
  ["EF05MA12", "ALGEBRA", "Resolver problemas envolvendo a partilha de uma quantidade em duas partes desiguais, envolvendo relações de proporcionalidade direta."],
  ["EF05MA13", "ALGEBRA", "Resolver e elaborar problemas envolvendo relações de proporcionalidade direta entre duas grandezas."],
  ["EF05MA14", "GEOMETRIA", "Utilizar e compreender diferentes representações para a localização de objetos no plano, como mapas, croquis e outras representações gráficas."],
  ["EF05MA15", "GEOMETRIA", "Interpretar, descrever e representar a localização de pontos em sistema de coordenadas cartesianas, no primeiro quadrante."],
  ["EF05MA16", "GEOMETRIA", "Associar figuras geométricas espaciais a suas planificações e analisar, nomear e comparar seus atributos."],
  ["EF05MA17", "GEOMETRIA", "Reconhecer, nomear e comparar polígonos, considerando lados, vértices e ângulos, e desenhá-los usando malhas quadriculadas."],
  ["EF05MA18", "GEOMETRIA", "Reconhecer a congruência dos ângulos e a proporcionalidade entre os lados correspondentes de figuras poligonais em situações de ampliação e de redução em malhas quadriculadas."],
  ["EF05MA19", "GRANDEZAS_MEDIDAS", "Resolver e elaborar problemas envolvendo medidas das grandezas comprimento, área, massa, tempo, temperatura e capacidade, recorrendo a transformações entre unidades."],
  ["EF05MA20", "GRANDEZAS_MEDIDAS", "Concluir, por meio de investigações, que figuras de perímetros iguais podem ter áreas diferentes e que, também, figuras que têm a mesma área podem ter perímetros diferentes."],
  ["EF05MA21", "GRANDEZAS_MEDIDAS", "Reconhecer volume como grandeza associada a sólidos geométricos e medir volumes por meio de empilhamento de cubos."],
  ["EF05MA22", "PROBABILIDADE_ESTATISTICA", "Apresentar todos os possíveis resultados de um experimento aleatório, estimando se esses resultados são igualmente prováveis ou não."],
  ["EF05MA23", "PROBABILIDADE_ESTATISTICA", "Determinar a probabilidade de ocorrência de um resultado em eventos aleatórios, quando todos os resultados possíveis têm a mesma chance de ocorrer."],
  ["EF05MA24", "PROBABILIDADE_ESTATISTICA", "Interpretar dados estatísticos apresentados em textos, tabelas e gráficos, referentes a outras áreas do conhecimento ou a outros contextos."],
  ["EF05MA25", "PROBABILIDADE_ESTATISTICA", "Coletar, classificar e representar dados por meio de tabelas e gráficos, e interpretar informações apresentadas."],
];

const ANO_6: RawHabilidade[] = [
  ["EF06MA01", "NUMEROS", "Comparar, ordenar, ler e escrever números naturais e números racionais cuja representação decimal é finita, utilizando a reta numérica."],
  ["EF06MA02", "NUMEROS", "Reconhecer o sistema de numeração decimal como o que prevaleceu no mundo ocidental, destacando semelhanças e diferenças com outros sistemas."],
  ["EF06MA03", "NUMEROS", "Resolver e elaborar problemas que envolvam cálculos com números naturais, por meio de estratégias variadas."],
  ["EF06MA04", "ALGEBRA", "Construir algoritmo em linguagem natural e representá-lo por fluxograma que indique a resolução de um problema simples."],
  ["EF06MA05", "NUMEROS", "Classificar números naturais em primos e compostos, estabelecer relações entre números e critérios de divisibilidade."],
  ["EF06MA06", "NUMEROS", "Resolver e elaborar problemas que envolvam as ideias de múltiplo e de divisor."],
  ["EF06MA07", "NUMEROS", "Compreender, comparar e ordenar frações associadas às ideias de partes de inteiros e resultado de divisão."],
  ["EF06MA08", "NUMEROS", "Reconhecer que os números racionais positivos podem ser expressos nas formas fracionária e decimal, estabelecendo relações entre elas."],
  ["EF06MA09", "NUMEROS", "Resolver e elaborar problemas que envolvam o cálculo da fração de uma quantidade e cujo resultado seja um número natural."],
  ["EF06MA10", "NUMEROS", "Resolver e elaborar problemas que envolvam adição ou subtração com números racionais positivos na representação fracionária."],
  ["EF06MA11", "NUMEROS", "Resolver e elaborar problemas que envolvam as quatro operações com números racionais positivos na representação decimal."],
  ["EF06MA12", "NUMEROS", "Fazer estimativas de quantidades e aproximar números para múltiplos da potência de 10 mais próxima."],
  ["EF06MA13", "NUMEROS", "Resolver e elaborar problemas que envolvam porcentagens, com base na ideia de proporcionalidade."],
  ["EF06MA14", "ALGEBRA", "Reconhecer que a relação de igualdade matemática não se altera ao adicionar, subtrair, multiplicar ou dividir os dois membros por um mesmo número."],
  ["EF06MA15", "ALGEBRA", "Resolver e elaborar problemas que envolvam a partilha de uma quantidade em duas partes desiguais."],
  ["EF06MA16", "GEOMETRIA", "Associar pares ordenados de números a pontos do plano cartesiano do 1º quadrante."],
  ["EF06MA17", "GEOMETRIA", "Quantificar e estabelecer relações entre o número de vértices, faces e arestas de prismas e pirâmides."],
  ["EF06MA18", "GEOMETRIA", "Reconhecer, nomear e comparar polígonos, considerando lados, vértices e ângulos."],
  ["EF06MA19", "GEOMETRIA", "Identificar características dos triângulos e classificá-los em relação às medidas dos lados e dos ângulos."],
  ["EF06MA20", "GEOMETRIA", "Identificar características dos quadriláteros, classificá-los em relação a lados e a ângulos e reconhecer a inclusão de classes entre eles."],
  ["EF06MA21", "GEOMETRIA", "Construir figuras planas semelhantes em situações de ampliação e de redução, com o uso de malhas quadriculadas."],
  ["EF06MA22", "GEOMETRIA", "Utilizar instrumentos, como régua e esquadros, ou softwares para representações de retas paralelas e perpendiculares."],
  ["EF06MA23", "GEOMETRIA", "Construir algoritmo para resolver situações passo a passo, como a construção de dobraduras ou a indicação de deslocamento de um objeto no plano."],
  ["EF06MA24", "GRANDEZAS_MEDIDAS", "Resolver e elaborar problemas que envolvam as grandezas comprimento, massa, tempo, temperatura, área e volume."],
  ["EF06MA25", "GEOMETRIA", "Reconhecer a abertura do ângulo como grandeza associada às figuras geométricas."],
  ["EF06MA26", "GEOMETRIA", "Resolver problemas que envolvam a noção de ângulo em diferentes contextos e em situações reais."],
  ["EF06MA27", "GEOMETRIA", "Determinar medidas da abertura de ângulos, com o uso de transferidor e/ou tecnologias digitais."],
  ["EF06MA28", "GEOMETRIA", "Interpretar, descrever e desenhar plantas baixas simples e vistas aéreas de espaços conhecidos, indicando pontos de referência."],
  ["EF06MA29", "GRANDEZAS_MEDIDAS", "Analisar e descrever mudanças que ocorrem no perímetro e na área de um quadrado ao se ampliarem ou reduzirem as medidas de seus lados."],
  ["EF06MA30", "PROBABILIDADE_ESTATISTICA", "Calcular a probabilidade de um evento aleatório, expressando-a por número racional e associando essa probabilidade a um percentual."],
  ["EF06MA31", "PROBABILIDADE_ESTATISTICA", "Identificar as variáveis e a possível relação entre elas em diferentes tipos de gráfico."],
  ["EF06MA32", "PROBABILIDADE_ESTATISTICA", "Interpretar e resolver situações que envolvam dados de pesquisas apresentadas em tabelas e em gráficos de colunas ou de setores."],
  ["EF06MA33", "PROBABILIDADE_ESTATISTICA", "Planejar e coletar dados de pesquisa envolvendo variáveis categóricas e numéricas e organizar os dados coletados em tabelas."],
  ["EF06MA34", "PROBABILIDADE_ESTATISTICA", "Interpretar e desenvolver fluxogramas simples, identificando as relações entre os objetos representados."],
];

const ANO_7: RawHabilidade[] = [
  ["EF07MA01", "NUMEROS", "Resolver e elaborar problemas com números naturais, envolvendo as noções de divisor e de múltiplo, podendo incluir máximo divisor comum ou mínimo múltiplo comum."],
  ["EF07MA02", "NUMEROS", "Resolver e elaborar problemas que envolvam porcentagens, com base na ideia de proporcionalidade, envolvendo acréscimos e decréscimos simples."],
  ["EF07MA03", "NUMEROS", "Comparar e ordenar números inteiros em diferentes contextos, incluindo o histórico, associando-os a pontos da reta numérica."],
  ["EF07MA04", "NUMEROS", "Resolver e elaborar problemas que envolvam operações com números inteiros."],
  ["EF07MA05", "NUMEROS", "Resolver um mesmo problema utilizando diferentes algoritmos."],
  ["EF07MA06", "NUMEROS", "Reconhecer que problemas diferentes podem ter a mesma estrutura matemática e, por isso, podem ser resolvidos pela mesma sequência de operações."],
  ["EF07MA07", "NUMEROS", "Representar por meio de um fluxograma os passos utilizados para resolver um grupo de problemas."],
  ["EF07MA08", "NUMEROS", "Comparar e ordenar frações associadas às ideias de partes de inteiros, resultado da divisão, razão e operador."],
  ["EF07MA09", "NUMEROS", "Utilizar, na resolução de problemas, a associação entre razão e fração, com o significado de proporção, para expressar relações entre grandezas."],
  ["EF07MA10", "NUMEROS", "Comparar e ordenar números racionais em diferentes contextos e associá-los a pontos na reta numérica."],
  ["EF07MA11", "NUMEROS", "Compreender e utilizar a multiplicação e a divisão de números racionais, a relação entre elas e suas propriedades operatórias."],
  ["EF07MA12", "NUMEROS", "Resolver e elaborar problemas que envolvam as operações com números racionais."],
  ["EF07MA13", "ALGEBRA", "Compreender as ideias de variável e de incógnita, expressas por letras ou outros símbolos, em diferentes contextos."],
  ["EF07MA14", "ALGEBRA", "Classificar sequências em recursivas e não recursivas, reconhecendo em uma sequência a expressão que gera regularidades."],
  ["EF07MA15", "ALGEBRA", "Utilizar a simbologia algébrica para expressar regularidades encontradas em sequências numéricas."],
  ["EF07MA16", "ALGEBRA", "Reconhecer se duas expressões algébricas obtidas para descrever a regularidade de uma mesma sequência numérica são ou não equivalentes."],
  ["EF07MA17", "ALGEBRA", "Resolver e elaborar problemas que envolvam variação de proporcionalidade direta e de proporcionalidade inversa entre duas grandezas."],
  ["EF07MA18", "ALGEBRA", "Resolver e elaborar problemas que possam ser representados por equações polinomiais de 1º grau, redutíveis à forma ax + b = c."],
  ["EF07MA19", "GEOMETRIA", "Realizar transformações de polígonos representados no plano cartesiano, decorrentes da multiplicação das coordenadas de seus vértices por um número inteiro."],
  ["EF07MA20", "GEOMETRIA", "Reconhecer e representar, no plano cartesiano, o simétrico de figuras em relação aos eixos e à origem."],
  ["EF07MA21", "GEOMETRIA", "Construir figuras planas semelhantes em situações de ampliação e redução, usando malhas quadriculadas, especialmente com o uso de tecnologias digitais."],
  ["EF07MA22", "GEOMETRIA", "Construir circunferências, utilizando compasso, reconhecê-las como lugar geométrico e utilizá-las para fazer composições artísticas."],
  ["EF07MA23", "GEOMETRIA", "Verificar relações entre os ângulos formados por retas paralelas cortadas por uma transversal, com e sem uso de softwares de geometria dinâmica."],
  ["EF07MA24", "GEOMETRIA", "Construir triângulos, reconhecer a condição de existência do triângulo quanto à medida dos lados e verificar a soma das medidas dos ângulos internos."],
  ["EF07MA25", "GEOMETRIA", "Reconhecer a rigidez geométrica dos triângulos e suas aplicações, como no caso de treliças e estruturas metálicas."],
  ["EF07MA26", "GEOMETRIA", "Descrever, por escrito e por meio de um fluxograma, um algoritmo para a construção de um triângulo qualquer, conhecidas as medidas dos três lados."],
  ["EF07MA27", "GEOMETRIA", "Calcular medidas de ângulos internos de polígonos regulares, sem o uso de fórmulas, e estabelecer relações entre os ângulos internos e externos."],
  ["EF07MA28", "GEOMETRIA", "Descrever, por escrito e por meio de um fluxograma, um algoritmo para a construção de um polígono regular, conhecida a medida de seu lado."],
  ["EF07MA29", "GRANDEZAS_MEDIDAS", "Resolver problemas de medições envolvendo grandezas em situações cotidianas, reconhecendo o caráter aproximado das medidas obtidas."],
  ["EF07MA30", "GRANDEZAS_MEDIDAS", "Resolver e elaborar problemas de cálculo de medida do volume de blocos retangulares, utilizando unidades de medida convencionais mais usuais."],
  ["EF07MA31", "GRANDEZAS_MEDIDAS", "Estabelecer expressões de cálculo para a área de triângulos e quadriláteros."],
  ["EF07MA32", "GRANDEZAS_MEDIDAS", "Resolver e elaborar problemas envolvendo o cálculo da área de figuras poligonais, decompondo-as em figuras cuja área de cálculo já seja conhecida."],
  ["EF07MA33", "GRANDEZAS_MEDIDAS", "Estabelecer o número π como a razão entre a medida de uma circunferência e seu diâmetro, para determinar a medida da circunferência."],
  ["EF07MA34", "PROBABILIDADE_ESTATISTICA", "Planejar e realizar experimentos aleatórios ou simulações que envolvem cálculo de probabilidade, com base na frequência de ocorrências."],
  ["EF07MA35", "PROBABILIDADE_ESTATISTICA", "Compreender, em contextos significativos, o significado de média estatística como indicador da tendência de uma pesquisa."],
  ["EF07MA36", "PROBABILIDADE_ESTATISTICA", "Planejar e realizar pesquisa envolvendo tema da realidade social e comunicar os resultados por meio de relatório contendo tabelas e gráficos."],
  ["EF07MA37", "PROBABILIDADE_ESTATISTICA", "Interpretar e analisar dados apresentados em gráfico de setores divulgados pela mídia e compreender quando é possível ou conveniente sua utilização."],
];

const ANO_8: RawHabilidade[] = [
  ["EF08MA01", "NUMEROS", "Efetuar cálculos com potências de expoentes inteiros e aplicar esse conhecimento na representação de números em notação científica."],
  ["EF08MA02", "NUMEROS", "Resolver e elaborar problemas usando a relação entre potenciação e radiciação, para representar uma raiz como potência de expoente fracionário."],
  ["EF08MA03", "NUMEROS", "Resolver e elaborar problemas de contagem cuja resolução envolva a aplicação do princípio multiplicativo."],
  ["EF08MA04", "NUMEROS", "Resolver e elaborar problemas, envolvendo cálculo de porcentagens, incluindo o uso de tecnologias digitais."],
  ["EF08MA05", "NUMEROS", "Reconhecer e utilizar procedimentos para a obtenção de uma fração geratriz para uma dízima periódica."],
  ["EF08MA06", "ALGEBRA", "Resolver e elaborar problemas que envolvam cálculo do valor numérico de expressões algébricas, utilizando as propriedades das operações."],
  ["EF08MA07", "ALGEBRA", "Associar uma equação linear de 1º grau com duas incógnitas a uma reta no plano cartesiano."],
  ["EF08MA08", "ALGEBRA", "Resolver e elaborar problemas relacionados ao seu contexto próximo, que possam ser representados por sistemas de equações de 1º grau com duas incógnitas."],
  ["EF08MA09", "ALGEBRA", "Resolver e elaborar problemas de contagem envolvendo o princípio multiplicativo, envolvendo equações polinomiais do tipo ax² = b."],
  ["EF08MA10", "ALGEBRA", "Identificar a regularidade de uma sequência numérica não recursiva e construir um algoritmo por meio de um fluxograma."],
  ["EF08MA11", "ALGEBRA", "Identificar a regularidade de uma sequência numérica recursiva e construir um algoritmo por meio de um fluxograma."],
  ["EF08MA12", "ALGEBRA", "Identificar a natureza da variação de duas grandezas diretamente ou inversamente proporcionais, ou não proporcionais."],
  ["EF08MA13", "ALGEBRA", "Resolver e elaborar problemas que envolvam grandezas diretamente ou inversamente proporcionais, por meio de estratégias variadas."],
  ["EF08MA14", "GEOMETRIA", "Demonstrar propriedades de quadriláteros por meio da identificação da congruência de triângulos."],
  ["EF08MA15", "GEOMETRIA", "Construir, utilizando instrumentos de desenho ou softwares, mediatriz, bissetriz, ângulos de 90°, 60°, 45° e 30° e polígonos regulares."],
  ["EF08MA16", "GEOMETRIA", "Descrever, por escrito e por meio de um fluxograma, um algoritmo para a construção de um hexágono regular de qualquer área, a partir da medida do lado."],
  ["EF08MA17", "GEOMETRIA", "Aplicar os conceitos de mediatriz e bissetriz como instrumentos de resolução de problemas, incluindo os que envolvam a construção de simétricos."],
  ["EF08MA18", "GEOMETRIA", "Reconhecer e construir figuras obtidas por composições de transformações geométricas (translação, reflexão e rotação), com o uso de instrumentos de desenho ou softwares."],
  ["EF08MA19", "GRANDEZAS_MEDIDAS", "Resolver e elaborar problemas que envolvam medidas de área de figuras geométricas planas."],
  ["EF08MA20", "GRANDEZAS_MEDIDAS", "Reconhecer a relação entre litro e decímetro cúbico e entre litro e metro cúbico, para resolver problemas de conversão de medidas de capacidade."],
  ["EF08MA21", "GRANDEZAS_MEDIDAS", "Resolver e elaborar problemas que envolvam medidas de volume de blocos retangulares, com o uso de unidades de medida convencionais mais usuais."],
  ["EF08MA22", "PROBABILIDADE_ESTATISTICA", "Calcular a probabilidade de eventos, com base na construção do espaço amostral, utilizando o princípio multiplicativo."],
  ["EF08MA23", "PROBABILIDADE_ESTATISTICA", "Avaliar a adequação de diferentes tipos de gráficos para representar um conjunto de dados."],
  ["EF08MA24", "PROBABILIDADE_ESTATISTICA", "Classificar as frequências de uma variável em classes, de modo que resulte em uma distribuição adequada, e representar esses dados por meio de gráficos."],
  ["EF08MA25", "PROBABILIDADE_ESTATISTICA", "Obter os valores de medidas de tendência central de uma pesquisa estatística (média, moda e mediana) e avaliar o comportamento de um conjunto de dados por meio da amplitude."],
  ["EF08MA26", "PROBABILIDADE_ESTATISTICA", "Selecionar amostras representativas de um universo pesquisado e reconhecer que as conclusões obtidas dependem da adequação da amostra."],
  ["EF08MA27", "PROBABILIDADE_ESTATISTICA", "Planejar e executar pesquisa amostral e comunicar seus resultados por meio de relatório contendo avaliação de medidas de tendência central e amplitude, tabelas e gráficos."],
];

const ANO_9: RawHabilidade[] = [
  ["EF09MA01", "NUMEROS", "Reconhecer que, uma vez fixada uma unidade de comprimento, existem segmentos de reta cujo comprimento não é expresso por número racional."],
  ["EF09MA02", "NUMEROS", "Reconhecer um número irracional como um número real cuja representação decimal é infinita e não periódica, e estimar a localização de alguns na reta numérica."],
  ["EF09MA03", "NUMEROS", "Efetuar cálculos com números reais, inclusive potências com expoentes fracionários."],
  ["EF09MA04", "NUMEROS", "Resolver e elaborar problemas com números reais, inclusive em notação científica, envolvendo diferentes operações."],
  ["EF09MA05", "NUMEROS", "Resolver e elaborar problemas que envolvam porcentagens, com base na análise de gráficos, incluindo o uso de tecnologias digitais."],
  ["EF09MA06", "ALGEBRA", "Compreender as funções como relações de dependência unívoca entre duas variáveis e suas representações numérica, algébrica e gráfica."],
  ["EF09MA07", "ALGEBRA", "Resolver e elaborar problemas que envolvam relações de proporcionalidade direta e inversa entre duas ou mais grandezas, inclusive escalas."],
  ["EF09MA08", "ALGEBRA", "Resolver e elaborar problemas que envolvam relações de proporcionalidade direta e inversa entre duas ou mais grandezas, sabendo diferenciá-las."],
  ["EF09MA09", "ALGEBRA", "Compreender os processos de fatoração de expressões algébricas, com base em suas relações com os produtos notáveis, para resolver e elaborar problemas."],
  ["EF09MA10", "GEOMETRIA", "Demonstrar relações simples entre os ângulos formados por retas paralelas cortadas por uma transversal."],
  ["EF09MA11", "GEOMETRIA", "Resolver problemas por meio do estabelecimento de relações entre arcos, ângulos centrais e ângulos inscritos na circunferência."],
  ["EF09MA12", "GEOMETRIA", "Reconhecer as condições necessárias e suficientes para que dois triângulos sejam semelhantes."],
  ["EF09MA13", "GEOMETRIA", "Demonstrar relações métricas do triângulo retângulo, entre elas o teorema de Pitágoras, utilizando, inclusive, a semelhança de triângulos."],
  ["EF09MA14", "GEOMETRIA", "Resolver e elaborar problemas de aplicação do teorema de Pitágoras ou das relações de proporcionalidade envolvendo retas paralelas cortadas por secantes."],
  ["EF09MA15", "GEOMETRIA", "Descrever, por escrito e por meio de um fluxograma, um algoritmo para a construção de um polígono regular cuja medida do lado é conhecida."],
  ["EF09MA16", "GEOMETRIA", "Determinar o ponto médio de um segmento de reta e a distância entre dois pontos quaisquer, dadas as coordenadas desses pontos no plano cartesiano, sem o uso de fórmulas."],
  ["EF09MA17", "GEOMETRIA", "Reconhecer vistas ortogonais de figuras espaciais e aplicar esse conhecimento para desenhar objetos em perspectiva."],
  ["EF09MA18", "GRANDEZAS_MEDIDAS", "Reconhecer e empregar unidades usadas para expressar medidas muito grandes ou muito pequenas, tais como distância entre planetas e tamanho de vírus."],
  ["EF09MA19", "GRANDEZAS_MEDIDAS", "Resolver e elaborar problemas que envolvam medidas de volumes de prismas e cilindros retos, inclusive com uso de expressões de cálculo."],
  ["EF09MA20", "PROBABILIDADE_ESTATISTICA", "Reconhecer, em experimentos aleatórios, eventos independentes e dependentes e calcular a probabilidade de sua ocorrência, nos dois casos."],
  ["EF09MA21", "PROBABILIDADE_ESTATISTICA", "Analisar e identificar, em gráficos divulgados pela mídia, os elementos que podem induzir a erros de leitura ou de interpretação."],
  ["EF09MA22", "PROBABILIDADE_ESTATISTICA", "Escolher e construir o gráfico mais adequado (colunas, setores, linhas) para apresentar um determinado conjunto de dados, destacando aspectos como as medidas de tendência central."],
  ["EF09MA23", "PROBABILIDADE_ESTATISTICA", "Planejar e executar pesquisa amostral envolvendo tema da realidade social e comunicar os resultados por meio de relatório contendo os gráficos apropriados."],
];

const POR_ANO: Record<number, RawHabilidade[]> = {
  1: ANO_1,
  2: ANO_2,
  3: ANO_3,
  4: ANO_4,
  5: ANO_5,
  6: ANO_6,
  7: ANO_7,
  8: ANO_8,
  9: ANO_9,
};

function distribuirBimestres(lista: RawHabilidade[]): HabilidadeSeed[] {
  const n = lista.length;
  return lista.map(([codigo, unidadeTematica, descricao], index) => {
    const bimestre = Math.min(4, Math.floor((index / n) * 4) + 1);
    return {
      codigo,
      anoEscolar: Number(codigo.slice(2, 4)),
      unidadeTematica,
      descricao,
      bimestre,
    };
  });
}

export const HABILIDADES: HabilidadeSeed[] = Object.values(POR_ANO).flatMap(distribuirBimestres);
